package edu.carroll.eatAndShare.backEnd.model;

import java.util.List;
import java.util.Objects;
import jakarta.persistence.*;

/**
 * Filename: User.java
 * Author: Andrias
 * Date: October 11, 2025
 *
 * Description:
 * Represents a user within the EatAndShare application. A user may own
 * multiple recipes and has credentials including username, password,
 * and email, along with basic profile information.
 *
 * This entity maps to the "user" table in the database and defines a
 * one-to-many relationship with Recipe.
 */

@Entity
@Table(name = "user")
public class User {

    /** Serialization identifier (best practice for entity classes). */
    private static final long serialVersionUID = 1L;

    /** Auto-generated primary key for the User entity. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    /** Unique username associated with this user. */
    @Column(name = "username", nullable = false, unique = true)
    private String username;

    /** User's password (stored as a hashed string). */
    @Column(name = "password", nullable = false)
    private String password;

    /** User's email address. */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /** User’s first name. */
    @Column(name = "first_name", nullable = false)
    private String firstName;

    /** User’s last name. */
    @Column(name = "last_name", nullable = false)
    private String lastName;

    /**
     * One-to-many relationship with Recipe.
     * A user may own multiple recipes.
     * Cascade and orphanRemoval ensure proper persistence and cleanup.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Recipe> recipes;

    /**
     * Returns the user's first name.
     *
     * @return the first name
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the user's first name.
     *
     * @param firstName the first name to assign
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Returns the user's last name.
     *
     * @return the last name
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the user's last name.
     *
     * @param lastName the last name to assign
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Returns the user ID.
     *
     * @return the unique user ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the user ID.
     * Typically auto-generated by the database.
     *
     * @param id the user ID to assign
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Returns the username.
     *
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username.
     *
     * @param username the username to assign
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Returns the password (hashed text).
     *
     * @return the hashed password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the user password. Must be hashed before storage.
     *
     * @param password the hashed password to assign
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns the email address.
     *
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the user's email address.
     *
     * @param email the email to assign
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /** End-of-line constant for formatted toString() output. */
    private static final String EOL = System.lineSeparator();

    /** Tab indentation constant for toString() formatting. */
    private static final String TAB = "\t";

    /**
     * Returns a string representation of the user object.
     * The password is masked for security reasons.
     *
     * @return formatted string representation of the user
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Login @ ").append(super.toString()).append("[").append(EOL);
        builder.append(TAB).append("username=").append(username).append(EOL);
        builder.append(TAB).append("hashedPassword=").append("****").append(EOL);
        builder.append(TAB).append("email=").append(email).append(EOL);
        builder.append("]").append(EOL);
        return builder.toString();
    }

    /**
     * Compares this User object with another for equality.
     * Equality is based on username, password, email, name fields, and recipes.
     *
     * @param o the object to compare with
     * @return true if the objects are equal; false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return Objects.equals(username, user.username) &&
                Objects.equals(password, user.password) &&
                Objects.equals(email, user.email) &&
                Objects.equals(firstName, user.firstName) &&
                Objects.equals(lastName, user.lastName) &&
                Objects.equals(recipes, user.recipes);
    }

    /**
     * Generates a hash code for this User object based on relevant fields.
     *
     * @return the generated hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(username, password, email, firstName, lastName, recipes);
    }
}
